import express from "express";
import bodyParser from "body-parser";
import employee from "./routes/employeeRoute";
import cors from "cors";
const app = express();
app.use(express.json());
app.use(cors());
app.use(bodyParser.json());
app.use("/api/v1", employee);
export default app;
